# Limpieza de datos: llegadas internacionales a Costa Rica


Este notebook prepara los datos de llegadas internacionales de turistas para su análisis.

- **Fuente:** Instituto Costarricense de Turismo (ICT), [Informes estadísticos](https://www.ict.go.cr/es/estadisticas/informes-estadisticos.html)
- **Archivo:** `Series_sitio_web_ICT_2025.xlsx`
- **Fecha de descarga:** 30/09/2026
- **Contenido:** llegadas internacionales por año y por país de origen.

**Objetivo:** limpiar y dar formato a los datos para guardarlos en `data/processed/` y usarlos en el análisis exploratorio.

## 1. Carga de datos

In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('../data/raw/Series_sitio_web_ICT_2025.xlsx', sheet_name='Todas_vías', header=None)

## 2. Exploración inicial

In [3]:
df.head(15)

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,CUADRO 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,LLEGADAS INTERNACIONALES A COSTA RICA Y VARIAC...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,"TODAS LAS VÍAS, SEGÚN ZONAS Y PAÍSES",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,2017-2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,PAISES Y/O \nZONAS,NaN,Año,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,2017,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,...,2020 - 2021,NaN,2021- 2022,NaN,2022- 2023,NaN,2023- 2024,NaN,2024- 2025,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Absoluta,%,Absoluta,%,Absoluta,%,Absoluta,%,Absoluta,%
10,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,TOTAL,NaN,2959869,3016667.0,3139008.0,1011912.0,1347055.0,2349537.0,2751134.0,...,335143,33.119777,1002482,74.420272,401597,17.092602,168349,6.119258,24508,0.839464
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,...,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
13,NaN,AMÉRICA DEL NORTE,NaN,1507945,1580991.0,1666571.0,571010.0,958792.0,1533502.0,1820038.0,...,387782,67.911595,574710,59.941051,286536,18.685075,169687,9.323267,9875,0.4963
14,NaN,NaN,Canadá,201921,217006.0,234621.0,115632.0,53185.0,183678.0,260744.0,...,-62447,-54.004947,130493,245.356774,77066,41.957121,11512,4.415058,1825,0.670325

In [4]:
df.tail(10)

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
73,NaN,NaN,Suecia,9985,11117.0,10979.0,4283.0,3690.0,7727.0,7207.0,...,-593,-13.845435,4037,109.403794,-520,-6.729649,102,1.415291,-74,-1.01245
74,NaN,NaN,Suiza,25395,28884.0,27841.0,10487.0,21643.0,29766.0,29429.0,...,11156,106.379327,8123,37.531765,-337,-1.132164,-2888,-9.813449,-2832,-10.670284
75,NaN,NaN,Otros Europa,10058,10673.0,11283.0,4564.0,7609.0,11868.0,13794.0,...,3045,66.717791,4259,55.97319,1926,16.228514,-648,-4.697695,498,3.788225
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,OTRAS ZONAS2,NaN,59671,60778.0,64143.0,15095.0,15352.0,33841.0,51404.0,...,257,1.702551,18489,120.43382,17563,51.898585,9675,18.821492,-3078,-5.039375
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,1/ La mayoría de las llegadas de Puerto Rico q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,"2/ Incluye la categoría Asia y El Pacífico, Áf...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,Fuente: ICT con datos de la Dirección General ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Observaciones

La hoja conserva el formato visual del Excel, por lo que los datos no empiezan en la primera fila:

- **Filas 0 a 10:** títulos y encabezados del cuadro. Los datos empiezan en la fila 11, con el TOTAL.
- **Columna 1:** regiones (TOTAL, AMÉRICA DEL NORTE, etc.), que funcionan como subtotales.
- **Columna 2:** países. Solo tienen valor en las filas de país; en las filas de región aparecen vacías.
- **Columnas 3 a 11:** llegadas de 2017 a 2025.
- **Columnas 12 a 27:** variaciones entre años, absolutas y porcentuales.
- **Últimas filas:** notas al pie y la fuente.
- **Columna 0:** vacía.

## 3. Limpieza

### Selección de filas y columnas

- **Filas 11 a 77:** contienen los datos de llegadas, desde el TOTAL hasta "OTRAS ZONAS". Las filas anteriores son títulos del cuadro y las posteriores son notas al pie y la fuente.
- **Columnas 1 a 11:** región, país y las llegadas de 2017 a 2025. Las columnas restantes son variaciones entre años (absolutas y porcentuales), que se descartan porque pueden calcularse a partir de los datos anuales.

In [5]:
datos = df.iloc[11:78,1:12].copy()
datos.head()

,1,2,3,4,5,6,7,8,9,10,11
11,TOTAL,NaN,2959869,3016667.0,3139008.0,1011912.0,1347055.0,2349537.0,2751134.0,2919483.0,2943991.0
12,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
13,AMÉRICA DEL NORTE,NaN,1507945,1580991.0,1666571.0,571010.0,958792.0,1533502.0,1820038.0,1989725.0,1999600.0
14,NaN,Canadá,201921,217006.0,234621.0,115632.0,53185.0,183678.0,260744.0,272256.0,274081.0
15,NaN,Estados Unidos,1199241,1265067.0,1334777.0,434775.0,868986.0,1290038.0,1473620.0,1621340.0,1627807.0

In [6]:
datos.shape

(67, 11)

### Nombres de columnas

Se asignan nombres descriptivos a las columnas: `region`, `pais` y un año por cada columna de llegadas (2017 a 2025).

In [7]:
datos.columns = ['region', 'pais', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']
datos.head()

,region,pais,2017,2018,2019,2020,2021,2022,2023,2024,2025
11,TOTAL,NaN,2959869,3016667.0,3139008.0,1011912.0,1347055.0,2349537.0,2751134.0,2919483.0,2943991.0
12,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
13,AMÉRICA DEL NORTE,NaN,1507945,1580991.0,1666571.0,571010.0,958792.0,1533502.0,1820038.0,1989725.0,1999600.0
14,NaN,Canadá,201921,217006.0,234621.0,115632.0,53185.0,183678.0,260744.0,272256.0,274081.0
15,NaN,Estados Unidos,1199241,1265067.0,1334777.0,434775.0,868986.0,1290038.0,1473620.0,1621340.0,1627807.0

### Región de cada país

En el archivo original, la región solo aparece en la fila de su subtotal, y los países debajo quedan vacíos en esa columna. Con `ffill()` se rellena cada vacío con el último valor de la fila superior, de modo que cada país quede asociado a su región.

In [8]:
datos['region'] = datos['region'].ffill()
datos.head()

,region,pais,2017,2018,2019,2020,2021,2022,2023,2024,2025
11,TOTAL,NaN,2959869,3016667.0,3139008.0,1011912.0,1347055.0,2349537.0,2751134.0,2919483.0,2943991.0
12,TOTAL,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
13,AMÉRICA DEL NORTE,NaN,1507945,1580991.0,1666571.0,571010.0,958792.0,1533502.0,1820038.0,1989725.0,1999600.0
14,AMÉRICA DEL NORTE,Canadá,201921,217006.0,234621.0,115632.0,53185.0,183678.0,260744.0,272256.0,274081.0
15,AMÉRICA DEL NORTE,Estados Unidos,1199241,1265067.0,1334777.0,434775.0,868986.0,1290038.0,1473620.0,1621340.0,1627807.0

### Filas que no corresponden a países

- **TOTAL y subtotales de región:** se eliminan porque pueden calcularse sumando los países.
- **Filas separadoras:** se eliminan porque no contienen información.
- **OTRAS ZONAS:**  se conserva. Agrupa Asia y el Pacífico, África y Oriente Medio, con alrededor de 60 000 turistas al año (cerca del 2 % del total). Eliminarla impediría analizar estas regiones y haría que la suma de los datos no coincidiera con el total oficial. Se le asigna "Otras zonas" como país y se elimina el "2" de la nota al pie.

In [9]:
datos[ datos['pais'].isna() ]

,region,pais,2017,2018,2019,2020,2021,2022,2023,2024,2025
11,TOTAL,NaN,2959869,3016667.0,3139008.0,1011912.0,1347055.0,2349537.0,2751134.0,2919483.0,2943991.0
12,TOTAL,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
13,AMÉRICA DEL NORTE,NaN,1507945,1580991.0,1666571.0,571010.0,958792.0,1533502.0,1820038.0,1989725.0,1999600.0
17,AMÉRICA DEL NORTE,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
18,AMÉRICA CENTRAL,NaN,735178,691386.0,698601.0,202374.0,78425.0,194242.0,235712.0,235860.0,247850.0
25,AMÉRICA CENTRAL,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
26,AMÉRICA DEL SUR,NaN,181399,190413.0,195581.0,50237.0,60221.0,110852.0,134399.0,136466.0,155589.0
40,AMÉRICA DEL SUR,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0
41,CARIBE,NaN,13381,12997.0,13510.0,3247.0,4452.0,7457.0,10062.0,10628.0,11309.0
51,CARIBE,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0
52,EUROPA,NaN,462295,480102.0,500602.0,169949.0,229813.0,469643.0,499519.0,485725.0,471642.0
76,EUROPA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,OTRAS ZONAS2,NaN,59671,60778.0,64143.0,15095.0,15352.0,33841.0,51404.0,61079.0,58001.0

In [10]:
datos.loc[datos['region'] == 'OTRAS ZONAS2', 'pais'] = 'Otras zonas'
datos.loc[datos['region'] == 'OTRAS ZONAS2', 'region'] = 'OTRAS ZONAS'
datos.tail()

,region,pais,2017,2018,2019,2020,2021,2022,2023,2024,2025
73,EUROPA,Suecia,9985,11117.0,10979.0,4283.0,3690.0,7727.0,7207.0,7309.0,7235.0
74,EUROPA,Suiza,25395,28884.0,27841.0,10487.0,21643.0,29766.0,29429.0,26541.0,23709.0
75,EUROPA,Otros Europa,10058,10673.0,11283.0,4564.0,7609.0,11868.0,13794.0,13146.0,13644.0
76,EUROPA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,OTRAS ZONAS,Otras zonas,59671,60778.0,64143.0,15095.0,15352.0,33841.0,51404.0,61079.0,58001.0

### Corrección de Puerto Rico

Se elimina la marca de la nota al pie en "Puerto Rico1". Según esa nota, la mayoría de los viajeros de Puerto Rico se registran como llegadas de Estados Unidos porque usan el pasaporte de ese país, lo que explica sus valores tan bajos.

Se observa un aumento inusual en 2025 (de 3 llegadas en 2024 a 156), que se revisará en el análisis exploratorio.

In [11]:
datos.loc[datos['pais'] == 'Puerto Rico1', 'pais'] = 'Puerto Rico'
datos[datos['pais'] == 'Puerto Rico']

    region         pais 2017  2018  2019  2020  2021  2022  2023  2024   2025
47  CARIBE  Puerto Rico   13   7.0   5.0   0.0   0.0   1.0   1.0   3.0  156.0

In [12]:
datos = datos[ datos['pais'].notna() ]
datos.shape

(55, 11)

### Validación

Se comprueba que la limpieza no eliminó ni duplicó datos. Para ello, se suman las llegadas de todos los países por año y se comparan con el TOTAL que reporta el ICT en el archivo original.

In [13]:
anios = ['2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

comparacion = pd.DataFrame({
    'suma_paises': datos[anios].sum().values,
    'total_ict': df.iloc[11, 3:12].values
}, index=anios)

comparacion['coincide'] = comparacion['suma_paises'] == comparacion['total_ict']
comparacion

     suma_paises  total_ict  coincide
2017     2959869    2959869      True
2018   3016667.0  3016667.0      True
2019   3139008.0  3139008.0      True
2020   1011912.0  1011912.0      True
2021   1347055.0  1347055.0      True
2022   2349537.0  2349537.0      True
2023   2751134.0  2751134.0      True
2024   2919483.0  2919483.0      True
2025   2943991.0  2943991.0      True

Las sumas coinciden con el total oficial en los nueve años, por lo que no se perdieron datos durante la limpieza.

### Transformación a formato largo

La tabla tiene formato ancho: un país por fila y un año por columna. Se transforma a formato largo con `pd.melt()`, de modo que cada fila representa un país en un año, con las columnas `region`, `pais`, `anio` y `llegadas`.

Este formato (conocido como *tidy data*) facilita agrupar, filtrar y graficar los datos, ya que el año pasa a ser una variable en lugar de estar repartido en nueve columnas. El resultado tiene 495 filas (55 orígenes × 9 años).

In [14]:
largo = pd.melt(
    datos,
    id_vars=['region', 'pais'],
    var_name='anio',
    value_name='llegadas'
)
print(largo.shape)
largo.head(10)

(495, 4)

              region            pais  anio llegadas
0  AMÉRICA DEL NORTE          Canadá  2017   201921
1  AMÉRICA DEL NORTE  Estados Unidos  2017  1199241
2  AMÉRICA DEL NORTE          México  2017   106783
3    AMÉRICA CENTRAL          Belice  2017      970
4    AMÉRICA CENTRAL     El Salvador  2017    81091
5    AMÉRICA CENTRAL       Guatemala  2017    78032
6    AMÉRICA CENTRAL        Honduras  2017    40300
7    AMÉRICA CENTRAL       Nicaragua  2017   429990
8    AMÉRICA CENTRAL          Panamá  2017   104795
9    AMÉRICA DEL SUR       Argentina  2017    30992

### Revisión de tipos y valores faltantes

Después de la transformación se revisa el tipo de dato de cada columna y la cantidad de valores vacíos. La columna `anio` quedó como texto y `llegadas` como `object`, por lo que ambas deben convertirse a números enteros. Además, `llegadas` tiene 4 valores vacíos que se analizan a continuación.

In [15]:
print(largo.dtypes)
largo.isna().sum()

region         str
pais           str
anio           str
llegadas    object
dtype: object

region      0
pais        0
anio        0
llegadas    4
dtype: int64

In [16]:
largo[ largo['llegadas'].isna() ]

              region             pais  anio llegadas
16   AMÉRICA DEL SUR  Guyana Francesa  2017      NaN
71   AMÉRICA DEL SUR  Guyana Francesa  2018      NaN
126  AMÉRICA DEL SUR  Guyana Francesa  2019      NaN
181  AMÉRICA DEL SUR  Guyana Francesa  2020      NaN

In [17]:
datos[ datos['pais'] == 'Guyana Francesa' ]

,region,pais,2017,2018,2019,2020,2021,2022,2023,2024,2025
34,AMÉRICA DEL SUR,Guyana Francesa,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1.0,0.0

### Valores faltantes

La columna `llegadas` tiene 4 valores vacíos, todos de Guyana Francesa entre 2017 y 2020. A partir de 2021 el ICT registra este país por separado (con valores entre 0 y 1), por lo que los vacíos indican que no había registro, no que no hubo llegadas. Probablemente esos viajeros se contabilizaban dentro de Francia.

Se decide conservar los valores como `NaN` para no inventar datos. La columna se convertirá al tipo `Int64`, que admite números enteros y valores vacíos. Esto no afecta el análisis, ya que las sumas y los promedios ignoran los valores vacíos.

In [18]:
largo['anio'] = largo['anio'].astype('int')
largo['llegadas'] = largo['llegadas'].astype('Int64')
largo.dtypes

region        str
pais          str
anio        int64
llegadas    Int64
dtype: object

## 4. Guardado de datos limpios

Se guarda la tabla final en `data/processed/llegadas_por_pais.csv`. El archivo contiene 495 filas (55 orígenes × 9 años) y cuatro columnas: `region`, `pais`, `anio` y `llegadas`. Este archivo es el punto de partida para el análisis exploratorio en `02_eda.ipynb`.

In [19]:
largo.to_csv('../data/processed/llegadas_por_pais.csv', index=False)

## 5. Limpieza de llegadas por vía aérea

Al revisar la hoja `Vía_aérea` se observa que tiene exactamente el mismo formato que `Todas_vías`, por lo que se aplica el mismo proceso de limpieza.

In [20]:
df_aerea = pd.read_excel('../data/raw/Series_sitio_web_ICT_2025.xlsx', sheet_name='Vía_aérea', header=None)

In [21]:
datos_aerea = df_aerea.iloc[11:78,1:12].copy()
datos_aerea.head()

,1,2,3,4,5,6,7,8,9,10,11
11,TOTAL,NaN,2189234,2314888.0,2418300.0,789833.0,1270483.0,2117960.0,2471150.0,2661488.0,2689278.0
12,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
13,AMÉRICA DEL NORTE,NaN,1420770,1512455.0,1592888.0,547466.0,937802.0,1480603.0,1756578.0,1936937.0,1949344.0
14,NaN,Canadá,182662,200320.0,218982.0,107964.0,49917.0,171033.0,242970.0,257395.0,260347.0
15,NaN,Estados Unidos,1137006,1217511.0,1283112.0,419978.0,852182.0,1252469.0,1431644.0,1587138.0,1594882.0

In [22]:
datos_aerea.columns = ['region', 'pais', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']
datos_aerea.head()

,region,pais,2017,2018,2019,2020,2021,2022,2023,2024,2025
11,TOTAL,NaN,2189234,2314888.0,2418300.0,789833.0,1270483.0,2117960.0,2471150.0,2661488.0,2689278.0
12,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
13,AMÉRICA DEL NORTE,NaN,1420770,1512455.0,1592888.0,547466.0,937802.0,1480603.0,1756578.0,1936937.0,1949344.0
14,NaN,Canadá,182662,200320.0,218982.0,107964.0,49917.0,171033.0,242970.0,257395.0,260347.0
15,NaN,Estados Unidos,1137006,1217511.0,1283112.0,419978.0,852182.0,1252469.0,1431644.0,1587138.0,1594882.0

In [23]:
datos_aerea['region'] = datos_aerea['region'].ffill()
datos_aerea.head()

,region,pais,2017,2018,2019,2020,2021,2022,2023,2024,2025
11,TOTAL,NaN,2189234,2314888.0,2418300.0,789833.0,1270483.0,2117960.0,2471150.0,2661488.0,2689278.0
12,TOTAL,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
13,AMÉRICA DEL NORTE,NaN,1420770,1512455.0,1592888.0,547466.0,937802.0,1480603.0,1756578.0,1936937.0,1949344.0
14,AMÉRICA DEL NORTE,Canadá,182662,200320.0,218982.0,107964.0,49917.0,171033.0,242970.0,257395.0,260347.0
15,AMÉRICA DEL NORTE,Estados Unidos,1137006,1217511.0,1283112.0,419978.0,852182.0,1252469.0,1431644.0,1587138.0,1594882.0

In [24]:
datos_aerea.loc[datos_aerea['region'] == 'OTRAS ZONAS2', 'pais'] = 'Otras zonas'
datos_aerea.loc[datos_aerea['region'] == 'OTRAS ZONAS2', 'region'] = 'OTRAS ZONAS'
datos_aerea.tail()

,region,pais,2017,2018,2019,2020,2021,2022,2023,2024,2025
73,EUROPA,Suecia,8238,9512.0,9805.0,3673.0,3437.0,6775.0,6230.0,6461.0,6369.0
74,EUROPA,Suiza,21464,25175.0,24692.0,9281.0,20547.0,26109.0,25473.0,23181.0,20924.0
75,EUROPA,Otros Europa,7882,8825.0,9284.0,3957.0,7185.0,10609.0,12028.0,11603.0,12091.0
76,EUROPA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,OTRAS ZONAS,Otras zonas,49840,52981.0,56295.0,12997.0,14052.0,29903.0,45077.0,54896.0,51971.0

In [25]:
datos_aerea.loc[datos_aerea['pais'] == 'Puerto Rico1', 'pais'] = 'Puerto Rico'
datos_aerea[datos_aerea['pais'] == 'Puerto Rico']

    region         pais 2017  2018  2019  2020  2021  2022  2023  2024   2025
47  CARIBE  Puerto Rico   13   7.0   5.0   0.0   0.0   1.0   0.0   3.0  155.0

In [26]:
datos_aerea = datos_aerea[ datos_aerea['pais'].notna() ]
datos_aerea.shape

(55, 11)

In [27]:
anios = ['2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025']

comparacion_aerea = pd.DataFrame({
    'suma_paises': datos_aerea[anios].sum().values,
    'total_ict': df_aerea.iloc[11, 3:12].values
}, index=anios)

comparacion_aerea['coincide'] = comparacion_aerea['suma_paises'] == comparacion_aerea['total_ict']
comparacion_aerea

     suma_paises  total_ict  coincide
2017     2189234    2189234      True
2018   2314888.0  2314888.0      True
2019   2418300.0  2418300.0      True
2020    789833.0   789833.0      True
2021   1270483.0  1270483.0      True
2022   2117960.0  2117960.0      True
2023   2471150.0  2471150.0      True
2024   2661488.0  2661488.0      True
2025   2689278.0  2689278.0      True

In [28]:
largo_aerea = pd.melt(
    datos_aerea,
    id_vars=['region', 'pais'],
    var_name='anio',
    value_name='llegadas_aereas'
)
print(largo_aerea.shape)
largo_aerea.head(10)

(495, 4)

              region            pais  anio llegadas_aereas
0  AMÉRICA DEL NORTE          Canadá  2017          182662
1  AMÉRICA DEL NORTE  Estados Unidos  2017         1137006
2  AMÉRICA DEL NORTE          México  2017          101102
3    AMÉRICA CENTRAL          Belice  2017             839
4    AMÉRICA CENTRAL     El Salvador  2017           37538
5    AMÉRICA CENTRAL       Guatemala  2017           52207
6    AMÉRICA CENTRAL        Honduras  2017           15668
7    AMÉRICA CENTRAL       Nicaragua  2017           21246
8    AMÉRICA CENTRAL          Panamá  2017           37523
9    AMÉRICA DEL SUR       Argentina  2017           24474

In [29]:
largo_aerea['anio'] = largo_aerea['anio'].astype('int')
largo_aerea['llegadas_aereas'] = largo_aerea['llegadas_aereas'].astype('Int64')
largo_aerea.dtypes

region               str
pais                 str
anio               int64
llegadas_aereas    Int64
dtype: object

In [30]:
largo_aerea.to_csv('../data/processed/llegadas_aereas_por_pais.csv', index=False)

## Resumen

El dataset final contiene las llegadas internacionales a Costa Rica por país de origen entre 2017 y 2025:

- **495 filas y 4 columnas:** `region`, `pais`, `anio` y `llegadas`, en formato largo.
- **55 orígenes:** 52 países y 3 categorías agrupadas del ICT ("Otros Caribe", "Otros Europa" y "Otras zonas", que reúne Asia y el Pacífico, África y Oriente Medio).
- **4 valores faltantes:** Guyana Francesa entre 2017 y 2020, conservados como `NaN` porque el ICT no registraba ese país por separado.
- **Datos validados:** la suma de llegadas por año coincide con el total oficial del ICT en los nueve años.
- **Llegadas por vía aérea:** se aplicó la misma limpieza a la hoja `Vía_aérea` y se guardó en `llegadas_aereas_por_pais.csv`, con la misma estructura (495 filas) y la columna `llegadas_aereas`.